# This is a basic workflow to help you get started with Actions

name: Create Pre-Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: nyaa8/package-version@v1
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          bodyFile: "CHANGELOG.md"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'dev-${{ env.PACKAGE_VERSION }}'
